//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency04.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agency04.Resource.EmailInfo", typeof(EmailInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notifications.
        /// </summary>
        public static string EMAIL_SUBJECT_DEFAUALT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_DEFAUALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team_name@ag04.io.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email-smtp.eu-west-1.amazonaws.com.
        /// </summary>
        public static string SMTP_HOST {
            get {
                return ResourceManager.GetString("SMTP_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDVKBQLtJH5DFJ3isJMP80afrFXxjyIOKIMNrdyHw7aD.
        /// </summary>
        public static string SMTP_PASSWORD {
            get {
                return ResourceManager.GetString("SMTP_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25, 467, 587 .
        /// </summary>
        public static string SMTP_PORT {
            get {
                return ResourceManager.GetString("SMTP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKIA3QRJDSTT4P7LI2NJ.
        /// </summary>
        public static string SMTP_USERNAME {
            get {
                return ResourceManager.GetString("SMTP_USERNAME", resourceCulture);
            }
        }
    }
}
